#%RAML 1.0 NamedExample
value:
-
  customerID: 2
  customerName: Ivan
  customerSurname: Indjic
  vuvuzelaType: B
  vuvuzelaAmount: 300
-
  customerID: 3
  customerName: Ivan
  customerSurname: Indjic
  vuvuzelaType: A
  vuvuzelaAmount: 300
-
  customerID: 1
  customerName: Ivan
  customerSurname: Indjic
  vuvuzelaType: C
  vuvuzelaAmount: 300
  